version: '3.6'

services:
  web:
    image: ave-mairie-ia:web-dev
    build:
      context: apps/web
      target: dev
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - ./apps/web:/app
    restart: always